<template><view><PageHeader :title="parent?.name||category?.name||'作品'" back-button/><scroll-view v-if="siblings.length>1" scroll-x class="category-nav" :scroll-into-view="'cat-'+id"><view v-for="c in siblings" :id="'cat-'+c.id" :key="c.id" class="category" :class="{selected:c.id===id}" @click="select(c.id)">{{c.name}}</view></scroll-view><MediaVideo v-if="category?.list_video" :key="id" class="category-video" :src="media(category.list_video)" :poster="media(category.list_poster)" controls object-fit="cover"/><image v-if="category?.list_hd" class="category-art" :src="media(category.list_hd)" mode="widthFix"/><PostGrid :posts="posts" :articles="category?.pic_new"/><view class="load-state" @click="loadMore">{{error || (loading?'加载中…':hasMore?'加载更多':'已经到底了')}}</view><BrandFooter/></view></template>
<script setup>
import {ref,computed} from 'vue';import {onLoad,onReachBottom} from '@dcloudio/uni-app';import {request,categoryById,media,categories} from '../../lib/content';import PageHeader from '../../components/PageHeader.vue';import MediaVideo from '../../components/MediaVideo.vue';import PostGrid from '../../components/PostGrid.vue';import BrandFooter from '../../components/BrandFooter.vue';
const id=ref(0),posts=ref([]),loading=ref(false),error=ref(''),hasMore=ref(true);let cursor=0,page=1,sequence=0;
const category=computed(()=>categoryById(id.value)),parent=computed(()=>categoryById(category.value?.parent)),siblings=computed(()=>parent.value?.children||category.value?.children?.length&&category.value.children||[category.value].filter(Boolean));
async function select(value){id.value=Number(value);sequence++;posts.value=[];cursor=0;page=1;hasMore.value=true;loading.value=false;uni.pageScrollTo({scrollTop:0,duration:0});await loadMore()}
async function loadMore(){if(loading.value||!hasMore.value)return;loading.value=true;error.value='';const seq=sequence;try{const d=await request('post/list.json',{category_id:id.value,...(cursor?{cursor}:{paged:page})},page===1?'cat'+id.value:'cat'+id.value+'page'+page);if(seq!==sequence)return;posts.value=[...new Map([...posts.value,...d.posts].map(p=>[p.id,p])).values()];cursor=d.next_cursor;hasMore.value=page<d.total_pages&&d.posts.length>0;page++}catch(e){if(seq===sequence)error.value=e.message}finally{if(seq===sequence)loading.value=false}}
onLoad(o=>select(o.category_id||139));onReachBottom(loadMore)
</script>
<style scoped>.category-nav{white-space:nowrap;height:100rpx;background:#fff;position:relative}.category{display:inline-block;margin:0 22rpx;padding:28rpx 0 22rpx;font-size:26rpx;color:#999;height:82rpx}.category.selected{color:#111;border-bottom:3rpx solid #111}.category-video{width:100%;height:421rpx;display:block}.category-art{width:100%;display:block}.load-state{text-align:center;font-size:22rpx;color:#bbb;padding:50rpx 30rpx}</style>
