<template><view class="header-space"><view class="header" :class="{transparent,scrolled}"><button v-if="backButton" class="back" aria-label="返回" @click="back"><CrowIcon name="arrow-left"/></button><text v-if="title" class="title">{{title}}</text><button v-else-if="search" class="search" aria-label="搜索" @click="openSearch"><image :src="scrolled?'/static/ui/logo_en.svg':'/static/ui/logo_cn.svg'" mode="aspectFit"/><text>│</text><view class="magnify"/></button><!-- #ifndef MP-WEIXIN --><view class="capsule"><button aria-label="更多" @click="more">•••</button><text>│</text><button aria-label="收起" @click="back">━</button><text>│</text><button aria-label="首页" @click="home"><view class="circle"><view/></view></button></view><!-- #endif --></view></view></template>
<script setup>
import {back} from '../lib/content'
import CrowIcon from './CrowIcon.vue'
defineProps({title:String,search:Boolean,backButton:Boolean,transparent:Boolean,scrolled:Boolean})
const openSearch=()=>uni.navigateTo({url:'/pages/search/search'})
const home=()=>uni.switchTab({url:'/pages/index/index'})
const more=()=>uni.showActionSheet({itemList:['返回首页','联系客服'],success:({tapIndex})=>tapIndex?uni.navigateTo({url:'/pages/service/service'}):home()})
</script>
<style scoped>
.header-space{height:116rpx}.header{position:fixed;top:0;left:0;right:0;height:116rpx;background:rgba(255,255,255,.94);z-index:30;backdrop-filter:blur(12px)}button{padding:0;background:transparent;margin:0;line-height:1;border:0}.capsule{position:absolute;right:11rpx;top:47rpx;width:215rpx;height:58rpx;display:flex;align-items:center;border:1rpx solid #e7e7e7;border-radius:40rpx;background:#fff}.capsule button{flex:1;height:56rpx;display:flex;align-items:center;justify-content:center;font-size:31rpx;font-weight:700}.capsule text{color:#d6d6d6;font-size:27rpx;font-weight:200}.circle{width:30rpx;height:30rpx;border:4rpx solid #222;border-radius:50%;display:flex;align-items:center;justify-content:center}.circle view{width:11rpx;height:11rpx;background:#222;border-radius:50%}.search{position:absolute;left:20rpx;top:47rpx;border:1rpx solid #eee;border-radius:40rpx;width:176rpx;height:58rpx;display:flex;align-items:center;justify-content:center;gap:14rpx}.search image{width:67rpx;height:32rpx}.search text{font-size:24rpx;color:#ddd}.magnify{width:18rpx;height:18rpx;border:2rpx solid #111;border-radius:50%;position:relative}.magnify:after{content:'';width:8rpx;height:2rpx;background:#111;position:absolute;right:-6rpx;bottom:-3rpx;transform:rotate(45deg)}.header.transparent{background:transparent;backdrop-filter:none}.header.transparent.scrolled{background:rgba(255,255,255,.9)}.search{background:#ffffffeb}.title{position:absolute;top:61rpx;left:50%;width:300rpx;transform:translateX(-50%);text-align:center;font-size:14px;line-height:32rpx;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.back{position:absolute;left:20rpx;top:47rpx;font-size:22px;width:40rpx;height:58rpx;display:flex;align-items:center;justify-content:center;font-weight:300}
</style>
